version: "3.9"
services :
  redis:
    container_name: redis_esperence
    image: "redislabs/redisearch:edge"
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

        